create table carts (
    id         bigint generated by default as identity primary key,
    token      varchar(64) not null,
    state      varchar(24) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint chk_carts_token_not_blank check (length(trim(token)) > 0),
    constraint chk_carts_state check (state in ('ACTIVE', 'CHECKED_OUT', 'ABANDONED')),
    constraint uq_carts_token unique (token)
);

create table cart_items (
    id         bigint generated by default as identity primary key,
    cart_id    bigint not null,
    product_id bigint not null,
    quantity   integer not null,
    constraint chk_cart_items_quantity check (quantity between 1 and 99),
    constraint fk_cart_items_cart foreign key (cart_id) references carts (id),
    constraint fk_cart_items_product foreign key (product_id) references products (id),
    constraint uq_cart_items_cart_product unique (cart_id, product_id)
);

create index idx_carts_token_state on carts (token, state);
create index idx_cart_items_cart on cart_items (cart_id);
