alter table products add column slug varchar(120);

update products set slug = 'anchovies-50g'               where name = 'Anchovies';
update products set slug = 'apples-1kg'                  where name = 'Apples';
update products set slug = 'arborio-rice-500g'           where name = 'Arborio rice';
update products set slug = 'artichoke-hearts-280g'       where name = 'Artichoke hearts';
update products set slug = 'asparagus-250g'              where name = 'Asparagus';
update products set slug = 'aubergines-500g'             where name = 'Aubergines';
update products set slug = 'avocados-400g'               where name = 'Avocados';
update products set slug = 'baby-spinach-200g'           where name = 'Baby spinach';
update products set slug = 'bacon-200g'                  where name = 'Bacon';
update products set slug = 'balsamic-vinegar-250ml'      where name = 'Balsamic vinegar';
update products set slug = 'bananas-1kg'                 where name = 'Bananas';
update products set slug = 'barbecue-sauce-400ml'        where name = 'Barbecue sauce';
update products set slug = 'basmati-rice-1kg'            where name = 'Basmati rice';
update products set slug = 'beef-burgers-400g'           where name = 'Beef burgers';
update products set slug = 'beef-mince-500g'             where name = 'Beef mince';
update products set slug = 'beef-steak-400g'             where name = 'Beef steak';
update products set slug = 'beef-strips-400g'            where name = 'Beef strips';
update products set slug = 'beetroot-500g'               where name = 'Beetroot';
update products set slug = 'black-beans-400g'            where name = 'Black beans';
update products set slug = 'black-pepper-50g'            where name = 'Black pepper';
update products set slug = 'blueberries-250g'            where name = 'Blueberries';
update products set slug = 'borlotti-beans-400g'         where name = 'Borlotti beans';
update products set slug = 'breadcrumbs-250g'            where name = 'Breadcrumbs';
update products set slug = 'breakfast-sausages-400g'     where name = 'Breakfast sausages';
update products set slug = 'broccoli-500g'               where name = 'Broccoli';
update products set slug = 'brown-rice-500g'             where name = 'Brown rice';
update products set slug = 'brussels-sprouts-500g'       where name = 'Brussels sprouts';
update products set slug = 'bulgur-wheat-500g'           where name = 'Bulgur wheat';
update products set slug = 'burger-buns-300g'            where name = 'Burger buns';
update products set slug = 'butter-250g'                 where name = 'Butter';
update products set slug = 'butter-beans-400g'           where name = 'Butter beans';
update products set slug = 'butternut-squash-1kg'        where name = 'Butternut squash';
update products set slug = 'cabbage-1kg'                 where name = 'Cabbage';
update products set slug = 'calamari-rings-400g'         where name = 'Calamari rings';
update products set slug = 'cannellini-beans-400g'       where name = 'Cannellini beans';
update products set slug = 'capers-100g'                 where name = 'Capers';
update products set slug = 'carrots-1kg'                 where name = 'Carrots';
update products set slug = 'cauliflower-1kg'             where name = 'Cauliflower';
update products set slug = 'celery-400g'                 where name = 'Celery';
update products set slug = 'cheddar-400g'                where name = 'Cheddar';
update products set slug = 'cherry-tomatoes-250g'        where name = 'Cherry tomatoes';
update products set slug = 'chicken-breast-500g'         where name = 'Chicken breast';
update products set slug = 'chicken-mince-500g'          where name = 'Chicken mince';
update products set slug = 'chicken-stock-500ml'         where name = 'Chicken stock';
update products set slug = 'chicken-thighs-600g'         where name = 'Chicken thighs';
update products set slug = 'chickpeas-400g'              where name = 'Chickpeas';
update products set slug = 'chilli-flakes-35g'           where name = 'Chilli flakes';
update products set slug = 'chipotle-paste-100g'         where name = 'Chipotle paste';
update products set slug = 'chopped-tomatoes-400g'       where name = 'Chopped tomatoes';
update products set slug = 'coconut-cream-400ml'         where name = 'Coconut cream';
update products set slug = 'coconut-milk-400ml'          where name = 'Coconut milk';
update products set slug = 'cod-fillets-400g'            where name = 'Cod fillets';
update products set slug = 'coleslaw-mix-400g'           where name = 'Coleslaw mix';
update products set slug = 'cooked-peeled-prawns-300g'   where name = 'Cooked peeled prawns';
update products set slug = 'cooking-cream-200ml'         where name = 'Cooking cream';
update products set slug = 'corn-tortillas-300g'         where name = 'Corn tortillas';
update products set slug = 'cornflour-250g'              where name = 'Cornflour';
update products set slug = 'courgettes-500g'             where name = 'Courgettes';
update products set slug = 'couscous-500g'               where name = 'Couscous';
update products set slug = 'crab-meat-170g'              where name = 'Crab meat';
update products set slug = 'cream-cheese-200g'           where name = 'Cream cheese';
update products set slug = 'creme-fraiche-200g'          where name = 'Crème fraîche';
update products set slug = 'cucumber-300g'               where name = 'Cucumber';
update products set slug = 'curry-paste-200g'            where name = 'Curry paste';
update products set slug = 'curry-powder-50g'            where name = 'Curry powder';
update products set slug = 'dates-250g'                  where name = 'Dates';
update products set slug = 'dijon-mustard-200g'          where name = 'Dijon mustard';
update products set slug = 'dried-bay-leaves-10g'        where name = 'Dried bay leaves';
update products set slug = 'dried-chickpeas-500g'        where name = 'Dried chickpeas';
update products set slug = 'dried-oregano-20g'           where name = 'Dried oregano';
update products set slug = 'eggs-330g'                   where name = 'Eggs';
update products set slug = 'falafel-250g'                where name = 'Falafel';
update products set slug = 'feta-200g'                   where name = 'Feta';
update products set slug = 'fish-fingers-450g'           where name = 'Fish fingers';
update products set slug = 'fish-sauce-200ml'            where name = 'Fish sauce';
update products set slug = 'fresh-basil-30g'             where name = 'Fresh basil';
update products set slug = 'fresh-coriander-30g'         where name = 'Fresh coriander';
update products set slug = 'fresh-dill-30g'              where name = 'Fresh dill';
update products set slug = 'fresh-mint-30g'              where name = 'Fresh mint';
update products set slug = 'fresh-parsley-30g'           where name = 'Fresh parsley';
update products set slug = 'fresh-rosemary-30g'          where name = 'Fresh rosemary';
update products set slug = 'fresh-thyme-30g'             where name = 'Fresh thyme';
update products set slug = 'frozen-berries-500g'         where name = 'Frozen berries';
update products set slug = 'frozen-peas-500g'            where name = 'Frozen peas';
update products set slug = 'frozen-spinach-500g'         where name = 'Frozen spinach';
update products set slug = 'frozen-sweetcorn-500g'       where name = 'Frozen sweetcorn';
update products set slug = 'garam-masala-40g'            where name = 'Garam masala';
update products set slug = 'garlic-100g'                 where name = 'Garlic';
update products set slug = 'ginger-150g'                 where name = 'Ginger';
update products set slug = 'gnocchi-500g'                where name = 'Gnocchi';
update products set slug = 'gochujang-500g'              where name = 'Gochujang';
update products set slug = 'grapes-500g'                 where name = 'Grapes';
update products set slug = 'greek-yogurt-500g'           where name = 'Greek yogurt';
update products set slug = 'green-beans-400g'            where name = 'Green beans';
update products set slug = 'green-lentils-500g'          where name = 'Green lentils';
update products set slug = 'ground-cardamom-35g'         where name = 'Ground cardamom';
update products set slug = 'ground-coriander-40g'        where name = 'Ground coriander';
update products set slug = 'ground-cumin-40g'            where name = 'Ground cumin';
update products set slug = 'ground-turmeric-40g'         where name = 'Ground turmeric';
update products set slug = 'haddock-fillets-400g'        where name = 'Haddock fillets';
update products set slug = 'halloumi-250g'               where name = 'Halloumi';
update products set slug = 'harissa-130g'                where name = 'Harissa';
update products set slug = 'hash-browns-700g'            where name = 'Hash browns';
update products set slug = 'hot-chilli-sauce-150ml'      where name = 'Hot chilli sauce';
update products set slug = 'hummus-200g'                 where name = 'Hummus';
update products set slug = 'jasmine-rice-1kg'            where name = 'Jasmine rice';
update products set slug = 'kale-200g'                   where name = 'Kale';
update products set slug = 'ketchup-500ml'               where name = 'Ketchup';
update products set slug = 'kidney-beans-400g'           where name = 'Kidney beans';
update products set slug = 'lamb-chops-500g'             where name = 'Lamb chops';
update products set slug = 'lamb-mince-500g'             where name = 'Lamb mince';
update products set slug = 'lasagne-sheets-500g'         where name = 'Lasagne sheets';
update products set slug = 'leeks-500g'                  where name = 'Leeks';
update products set slug = 'lemons-300g'                 where name = 'Lemons';
update products set slug = 'lettuce-200g'                where name = 'Lettuce';
update products set slug = 'mackerel-fillets-250g'       where name = 'Mackerel fillets';
update products set slug = 'mozzarella-250g'             where name = 'Mozzarella';
update products set slug = 'mushrooms-400g'              where name = 'Mushrooms';
update products set slug = 'mussels-2kg'                 where name = 'Mussels';
update products set slug = 'naan-bread-320g'             where name = 'Naan bread';
update products set slug = 'olive-oil-500ml'             where name = 'Olive oil';
update products set slug = 'onions-1kg'                  where name = 'Onions';
update products set slug = 'passata-700ml'               where name = 'Passata';
update products set slug = 'pesto-190g'                  where name = 'Pesto';
update products set slug = 'pizza-dough-400g'            where name = 'Pizza dough';
update products set slug = 'pork-mince-500g'             where name = 'Pork mince';
update products set slug = 'potatoes-1kg'                where name = 'Potatoes';
update products set slug = 'prawns-300g'                 where name = 'Prawns';
update products set slug = 'puff-pastry-320g'            where name = 'Puff pastry';
update products set slug = 'quinoa-500g'                 where name = 'Quinoa';
update products set slug = 'red-lentils-500g'            where name = 'Red lentils';
update products set slug = 'red-peppers-500g'            where name = 'Red peppers';
update products set slug = 'salmon-fillets-400g'         where name = 'Salmon fillets';
update products set slug = 'sardines-120g'               where name = 'Sardines';
update products set slug = 'sea-bass-fillets-400g'       where name = 'Sea bass fillets';
update products set slug = 'smoked-salmon-200g'          where name = 'Smoked salmon';
update products set slug = 'sourdough-country-loaf-500g' where name = 'Sourdough Country Loaf';
update products set slug = 'soy-sauce-150ml'             where name = 'Soy sauce';
update products set slug = 'squid-400g'                  where name = 'Squid';
update products set slug = 'sweet-potatoes-1kg'          where name = 'Sweet potatoes';
update products set slug = 'sweetcorn-340g'              where name = 'Sweetcorn';
update products set slug = 'taco-shells-135g'            where name = 'Taco shells';
update products set slug = 'tofu-400g'                   where name = 'Tofu';
update products set slug = 'tortilla-chips-200g'         where name = 'Tortilla chips';
update products set slug = 'tortilla-wraps-320g'         where name = 'Tortilla wraps';
update products set slug = 'turkey-breast-750g'          where name = 'Turkey breast';
update products set slug = 'wholewheat-penne-500g'       where name = 'Wholewheat penne';
update products set slug = 'wholewheat-spaghetti-500g'   where name = 'Wholewheat spaghetti';

alter table products alter column slug set not null;
alter table products add constraint chk_products_slug_not_blank check (length(trim(slug)) > 0);
alter table products add constraint uq_products_slug unique (slug);
